[package]
name = "actix-casbin"
version = "0.1.0"
authors = ["Eason Chai <hackerchai.com@gmail.com>","Cheng JIANG <jiang.cheng@vip.163.com>"]
edition = "2018"
license = "Apache-2.0"
description = "An Actix actor for casbin"
homepage="https://github.com/casbin-rs/actix-casbin"
readme="README.md"

[lib]
name = "actix_casbin"
path = "src/lib.rs"

[dependencies]
actix = "0.9.0"
casbin =  "0.6.0"
actix-rt = "1.1.0"
tokio = { version = "0.2.18", features = ["sync"] }

[dev-dependencies]
tokio = { version = "0.2.18", features = [ "full" ] }