[package]
name = "actix-casbin"
version = "0.2.1"
authors = ["Eason Chai <hackerchai.com@gmail.com>","Cheng JIANG <jiang.cheng@vip.163.com>"]
edition = "2018"
license = "Apache-2.0"
description = "An Actix actor for casbin"
homepage="https://github.com/casbin-rs/actix-casbin"
readme="README.md"

[lib]
name = "actix_casbin"
path = "src/lib.rs"

[dependencies]
actix =  "0.9.0"
casbin = { version = "1.1.0", default-features = false, features = [ "incremental" ] }
tokio = { version = "0.2.21", default-features = false, optional = true }
async-std = { version = "1.6.2", default-features = false, optional = true }
futures = "0.3"

[features]
default = ["runtime-async-std"]

runtime-tokio = ["casbin/runtime-tokio", "tokio/sync"]
runtime-async-std = ["casbin/runtime-async-std", "async-std/std"]

[dev-dependencies]
tokio = { version = "0.2.21", features = [ "full" ] }
async-std = { version = "1.6.2", features = [ "attributes" ] }
actix-rt = "1.1.1"
